# Generated by Django 3.2.5 on 2021-07-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_privacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='description',
            field=models.TextField(default=False, max_length=1000, verbose_name='توضیحات'),
        ),
    ]
