# Generated by Django 3.2.5 on 2021-08-31 12:09

from django.db import migrations, models
import shop_product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='نام قالب')),
                ('type', models.CharField(max_length=120, verbose_name='نوع قالب')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop_product.models.upload_image_path, verbose_name='عکس')),
                ('active', models.BooleanField(verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'محصولات',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
