# Generated by Django 3.2.5 on 2021-09-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_category', '0001_initial'),
        ('shop_product', '0002_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop_category.Category'),
        ),
    ]
