# Generated by Django 3.2.5 on 2021-09-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=120, verbose_name='توضیحات'),
        ),
    ]
