# Generated by Django 3.2.5 on 2021-09-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_comment', '0002_alter_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='product',
        ),
    ]
