# Generated by Django 3.2.5 on 2021-07-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide1', models.CharField(max_length=120, verbose_name='راهنمای 1')),
                ('guide2', models.CharField(max_length=120, verbose_name='راهنمای 2')),
                ('guide3', models.CharField(max_length=120, verbose_name='راهنمای 3')),
            ],
            options={
                'verbose_name': 'راهنمای سایت',
                'verbose_name_plural': 'راهنمای سایت',
            },
        ),
    ]
