# Generated by Django 3.2.5 on 2021-07-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='title',
            field=models.CharField(default=False, max_length=120, verbose_name='عنوان'),
        ),
    ]
