# Generated by Django 3.2.5 on 2021-07-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=120, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=120, verbose_name='عنوان پیام')),
                ('text', models.TextField(max_length=1000, verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده/ نشده')),
            ],
        ),
    ]
