# Generated by Django 3.2.5 on 2021-07-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس با ما'},
        ),
    ]
